export const gamesResponse = {
  games: [
    'Team Fortress 2',
    'Left 4 Dead 2',
    'Counter - Strike 2',
    "Garry's Mod",
    "Sid Meier's Civilization V",
    'Tribes: Ascend',
    'Sanctum',
    'Terraria',
    'Realm of the Mad God Exalt',
    'PlanetSide 2',
    'Insurgency',
    'Blade Symphony',
    'Path of Exile',
    'The Forest',
    'Space Engineers',
    'Risk of Rain(2013)',
    'Rocket League',
    'Fistful of Frags',
    'Evolve Stage 2',
    'Brawlhalla',
    'Unturned',
    "Don't Starve Together",
    'Dirty Bomb',
    'Dead by Daylight',
    'SMITE',
    'Faeria',
    'Minion Masters',
    'Deep Rock Galactic',
    'Quake Champions',
    'Stick Fight: The Game',
    'Valheim',
    'Among Us',
    'Enemy On Board',
    'PlanetSide 2 - Test',
    'King of Crabs',
    'Risk of Rain Returns',
  ]
}